### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [tomsrocket/toms-linkliste#1]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/tomsrocket/toms-linkliste/blob/master/scripts/package.json#L7

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by tomsrocket** [comment]
Thanks for the mentioning this, and sorry I didn't notice it for 4 months ....
I removed it now.
